package minimax;

public class Main {


	public static void main(String[] args) {
		// TODO Autogenerated method stub

	}

	//Returns an action
	public Action a_b_search(State state){

		int v = maxVal(state, -1000000, 1000000);
		//Todo: return the action in Successors(state) with value v
	}

	//Returns a utility value
	public int maxVal(State state, int alpha, int beta){

		if (terminalTest(state)){
			return utility(state);
		}

		int v = -1000000;

		for (State successorState: statesList){
			int v = Math.max(v, minVal(successorState, alpha, beta));
			if (v >= beta) {
				return v;
			}
			alpha = Math.max(alpha, v);
		}
		return v;

	}

	//Returns a utility value
	public int minVal(State state, int alpha, int beta){
		
		if (terminalTest(state)) {
			return utility
		}
	}
}
